name: frc8020_starting_pos_chart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  form_ui: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  inno_bundle: ^0.8.0


inno_bundle:
  id: 32241992-793a-4e5f-aee9-ffff78b119d5 # <-- Put your app id here
  publisher: YCY # Optional, but recommended.
  name: FRC Starting Position Viewer # 
  admin: auto
  languages:
    - english
  installer_icon: assets/icon/64.ico


flutter:
  uses-material-design: true
  assets:
    - assets/img/


# flutter pub get
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  image_path_ios_dark_transparent: assets/icon/icon_dark.png
  image_path_ios_tinted_grayscale: assets/icon/icon_grey.png
  desaturate_tinted_to_grayscale_ios: true
  color: "#f3f2f7"
  color_dark: "#000000"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows: 
    image_path: "assets/icon/icon_dark.png"
    generate: true
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/icon.png"